package com.jojolaptech.camel.model.postgres.enums;

import lombok.Getter;

@Getter
public enum CountryEnum {

    AF("Afghanistan"),
    AL("Albania"),
    DZ("Algeria"),
    AS("American Samoa"),
    AD("Andorra"),
    AO("Angola"),
    AR("Argentina"),
    AM("Armenia"),
    AU("Australia"),
    AT("Austria"),
    AZ("Azerbaijan"),
    BH("Bahrain"),
    BD("Bangladesh"),
    BY("Belarus"),
    BE("Belgium"),
    BT("Bhutan"),
    BO("Bolivia"),
    BA("Bosnia and Herzegovina"),
    BW("Botswana"),
    BR("Brazil"),
    BN("Brunei Darussalam"),
    BG("Bulgaria"),
    KH("Cambodia"),
    CM("Cameroon"),
    CA("Canada"),
    CL("Chile"),
    CN("China"),
    CO("Colombia"),
    CR("Costa Rica"),
    HR("Croatia"),
    CU("Cuba"),
    CY("Cyprus"),
    CZ("Czechia"),
    DK("Denmark"),
    DO("Dominican Republic"),
    EC("Ecuador"),
    EG("Egypt"),
    SV("El Salvador"),
    EE("Estonia"),
    ET("Ethiopia"),
    FI("Finland"),
    FR("France"),
    GE("Georgia"),
    DE("Germany"),
    GH("Ghana"),
    GR("Greece"),
    GT("Guatemala"),
    HN("Honduras"),
    HK("Hong Kong"),
    HU("Hungary"),
    IS("Iceland"),
    IN("India"),
    ID("Indonesia"),
    IR("Iran"),
    IQ("Iraq"),
    IE("Ireland"),
    IL("Israel"),
    IT("Italy"),
    JP("Japan"),
    JO("Jordan"),
    KZ("Kazakhstan"),
    KE("Kenya"),
    KR("Korea, Republic of"),
    KW("Kuwait"),
    KG("Kyrgyzstan"),
    LA("Lao People’s Democratic Republic"),
    LV("Latvia"),
    LB("Lebanon"),
    LY("Libya"),
    LT("Lithuania"),
    LU("Luxembourg"),
    MO("Macao"),
    MG("Madagascar"),
    MY("Malaysia"),
    MV("Maldives"),
    ML("Mali"),
    MT("Malta"),
    MX("Mexico"),
    MD("Moldova"),
    MC("Monaco"),
    MN("Mongolia"),
    ME("Montenegro"),
    MA("Morocco"),
    MZ("Mozambique"),
    MM("Myanmar"),
    NP("Nepal"),
    NL("Netherlands"),
    NZ("New Zealand"),
    NI("Nicaragua"),
    NG("Nigeria"),
    NO("Norway"),
    OM("Oman"),
    PK("Pakistan"),
    PS("Palestine"),
    PA("Panama"),
    PY("Paraguay"),
    PE("Peru"),
    PH("Philippines"),
    PL("Poland"),
    PT("Portugal"),
    QA("Qatar"),
    RO("Romania"),
    RU("Russian Federation"),
    RW("Rwanda"),
    SA("Saudi Arabia"),
    RS("Serbia"),
    SG("Singapore"),
    SK("Slovakia"),
    SI("Slovenia"),
    ZA("South Africa"),
    ES("Spain"),
    LK("Sri Lanka"),
    SE("Sweden"),
    CH("Switzerland"),
    TW("Taiwan"),
    TH("Thailand"),
    TR("Türkiye"),
    UA("Ukraine"),
    AE("United Arab Emirates"),
    GB("United Kingdom"),
    US("United States of America"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    VN("Viet Nam"),
    ZM("Zambia"),
    ZW("Zimbabwe");

    private final String country;

    CountryEnum(String country) {
        this.country = country;
    }

    public static CountryEnum fromCode(String code) {
        for (CountryEnum c : CountryEnum.values()) {
            if (c.name().equalsIgnoreCase(code)) {
                return c;
            }
        }
        throw new IllegalArgumentException("Unknown country code: " + code);
    }
}

