package com.jojolaptech.camel.model.postgres.enums;

import lombok.Getter;

@Getter
public enum LanguageEnum {

    AF("Afrikaans"),
    AM("Amharic"),
    AR("Arabic"),
    AZ("Azerbaijani"),
    BE("Belarusian"),
    BG("Bulgarian"),
    BN("Bengali"),
    BS("Bosnian"),
    CA("Catalan"),
    CS("Czech"),
    CY("Welsh"),
    DA("Danish"),
    DE("German"),
    EL("Greek"),
    EN("English"),
    EO("Esperanto"),
    ES("Spanish"),
    ET("Estonian"),
    EU("Basque"),
    FA("Persian"),
    FI("Finnish"),
    FIL("Filipino"),
    FO("Faroese"),
    FR("French"),
    GA("Irish"),
    GL("Galician"),
    GU("Gujarati"),
    HE("Hebrew"),
    HI("Hindi"),
    HR("Croatian"),
    HU("Hungarian"),
    HY("Armenian"),
    ID("Indonesian"),
    IS("Icelandic"),
    IT("Italian"),
    JA("Japanese"),
    JV("Javanese"),
    KA("Georgian"),
    KK("Kazakh"),
    KM("Khmer"),
    KN("Kannada"),
    KO("Korean"),
    KY("Kyrgyz"),
    LO("Lao"),
    LT("Lithuanian"),
    LV("Latvian"),
    MK("Macedonian"),
    ML("Malayalam"),
    MN("Mongolian"),
    MR("Marathi"),
    MS("Malay"),
    MT("Maltese"),
    MY("Burmese"),
    NE("Nepali"),
    NL("Dutch"),
    NO("Norwegian"),
    NY("Chichewa"),
    PA("Punjabi"),
    PL("Polish"),
    PS("Pashto"),
    PT("Portuguese"),
    RO("Romanian"),
    RU("Russian"),
    SD("Sindhi"),
    SI("Sinhala"),
    SK("Slovak"),
    SL("Slovenian"),
    SM("Samoan"),
    SN("Shona"),
    SO("Somali"),
    SQ("Albanian"),
    SR("Serbian"),
    ST("Sesotho"),
    SU("Sundanese"),
    SV("Swedish"),
    SW("Swahili"),
    TA("Tamil"),
    TE("Telugu"),
    TG("Tajik"),
    TH("Thai"),
    TL("Tagalog"),
    TR("Turkish"),
    TT("Tatar"),
    UK("Ukrainian"),
    UR("Urdu"),
    UZ("Uzbek"),
    VI("Vietnamese"),
    XH("Xhosa"),
    YO("Yoruba"),
    ZH("Chinese"),
    ZU("Zulu");

    private String language;

    LanguageEnum(String language) {
        this.language = language;
    }

}
